//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NOTLAR
    {
        public int ID { get; set; }
        public string TARIH { get; set; }
        public string SAAT { get; set; }
        public string BASLIK { get; set; }
        public string DETAY { get; set; }
        public string OLUSTURAN { get; set; }
        public string HITAP { get; set; }
    }
}
