//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SEHIRLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SEHIRLER()
        {
            this.TBL_ILCELER = new HashSet<TBL_ILCELER>();
        }
    
        public int SehirId { get; set; }
        public string SehirAdi { get; set; }
        public byte PlakaNo { get; set; }
        public int TelefonKodu { get; set; }
        public int RowNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ILCELER> TBL_ILCELER { get; set; }
    }
}
